### ISSUE TITLE
After kernel update mouse stopped working.

### ISSUE THREAD

**Issue by ParanoIIa91** [Gnarus-G/maccel#14]
After i reinstalled driver my mouse works again, but the problem is that applying same settings using "sudo maccel tui" does absolutely nothing?🤔

**Comment by Gnarus-G** [comment]
There is kind of already an issue I opened about this #7 

It sound like the driver did not bind automatically, which can happen in this case. You can check with `lsusb -t | grep maccel`. You can also run `sudo maccel bindall` to do the binding that would have happened automattically.

If the maccel is bound to your mouse and you don't think it works, then screenshot your settings, and give me the output of `cat /sys/module/maccel/parameters/*`.

P.S. You shouldn't need to run the tui with `sudo`, otherwise something went wrong in the install process.

**Comment by ParanoIIa91** [comment]
![Screenshot_20240430_075831](https://github.com/Gnarus-G/maccel/assets/74189594/2b2cce42-64aa-4d53-9834-0b89bad9fdc1)
![Screenshot_20240430_075858](https://github.com/Gnarus-G/maccel/assets/74189594/1602e69d-43f8-42a5-8363-2ed7e4aa7e9f)
If i use tui without sudo, it wont let me change anything and "lsusb -t | grep maccel" command gives me nothing?

**Comment by Gnarus-G** [comment]
Getting nothing means the driver isn't bound to any device. Run the bind all command I gave.

For the sudo on the tui, I guess you're fine with it. You probably didn't add yourself to the maccel group. So don't worry about it

**Comment by ParanoIIa91** [comment]
I done sudo bind all command before, but this time it worked, thanks :)

**Comment by Gnarus-G** [comment]
Great. I'll improve some of the documentation thanks to this issue.
