### ISSUE TITLE
Add other accel types

### ISSUE THREAD

**Issue by dougg0k** [Gnarus-G/maccel#31]
Hi,

Can you add other accel types like Motivity?

Also add anisotropy, to alter x / y of mouse independently? https://github.com/a1xd/rawaccel/blob/master/doc/Guide.md#horizontal-and-vertical

**Comment by Gnarus-G** [comment]
It's interesting to see that some people want this to be more like rawaccel. I'm iffy on wether I want feature parity with rawaccel, but I am not opposed to it. 
The issue is I don't yet understand the math past linear acceleration, and I don't have much time these days to dedicate to this project, but I will consider a pull request. For example Motivity is being worked on in #24

**Comment by dougg0k** [comment]
Not much about being like rawaccel, but the functionality in itself.

Those that were used by me and brought me the results I was looking for, no other accel type did.
